 algo: 'ppo'

 use_gail: True
 gail_experts_dir: '/home/kit/anthropomatik/kn6273/Repos/gail_experts/'
 gail_batch_size: 128
 gail_epoch: 5
 lr_disc: 1.0e-05
 num_trajectories: 4
 gradient_penalty: False
 spectral_norm: False
 airl_reward: False
 
 eps: 1.0e-5
 gamma: 0.99
 gae_lambda: 0.96
 entropy_coef: 0
 value_loss_coef: 1.0
 max_grad_norm: 0.5

 seed: 0
 cuda_deterministic: False
 num_processes: 1
 num_steps: 2048

 policy_epoch: 20

 mini_batch_size: 32
 clip_param: 0.2
 
 logging: False
 summary: False
 track_vf: False
 track_grad_kurtosis: False
 save_model: False
 log_interval: 2
 eval_interval: 4
 
 num_env_steps: 1.5e+6
 env_name: 'Walker2d-v2'
 logging_dir: './logs_gail_reward/'
 log_dir: '/home/kit/anthropomatik/kn6273/gym'
 cuda: False
 use_proper_time_limits: True

 gradient_clipping: False
 use_linear_lr_decay: False
 use_clipped_value_loss: False
 norm_obs: True
 norm_reward: False
 clip_obs: 1.0e+6
 clip_reward: 1.0e+6
 lr_policy: 0.0001
 lr_value: 0.0003

 clip_importance_ratio: False
 use_kl_penalty: False
 use_rollback: False
 use_tr_ppo: False
 use_truly_ppo: False
 use_gmom: False
 weiszfeld_iterations: 10

 rb_alpha: 5.0
 kl_target: 0.03
 start_beta: 1.0

 use_projection: True
 proj_type: 'kl'
 mean_bound: 0.009
 cov_bound: 5.0e-05
 trust_region_coeff: 16.0
 entropy_schedule: 'None'
 scale_prec: True
 entropy_eq: False
 entropy_first: True
 target_entropy: 0

 use_gae: True
 use_td: False
 use_disc_as_adv: False
 decay: 10.0
 gailgamma: 0.5
 bcgail: False