 algo: 'ppo'

 use_gail: True
 gail_experts_dir: '/home/kit/anthropomatik/kn6273/Repos/gail_experts/'
 gail_batch_size: 128
 gail_epoch: 5
 lr_disc: 1.0e-05
 num_trajectories: 4
 gradient_penalty: False
 spectral_norm: False
 airl_reward: False
 
 eps: 1.0e-5
 gamma: 0.97
 gae_lambda: 0.97
 entropy_coef: 0
 value_loss_coef: 1.0
 max_grad_norm: 0.5

 seed: 0
 cuda_deterministic: False
 num_processes: 1
 num_steps: 16384

 policy_epoch: 10

 mini_batch_size: 512
 clip_param: 0.2

 logging: False
 summary: False
 track_vf: True
 track_grad_kurtosis: False
 save_model: False
 log_interval: 2
 eval_interval: 4

 num_env_steps: 1.0e+6
 env_name: 'HalfCheetah-v2'
 logging_dir: './logs_gail_tr_ppo/'
 log_dir: '/home/kit/anthropomatik/kn6273/gym/'
 no_cuda: True
 use_proper_time_limits: True

 gradient_clipping: True
 use_linear_lr_decay: True
 use_clipped_value_loss: True
 norm_obs: True
 norm_reward: True
 clip_obs: 10.0
 clip_reward: 10.0
 lr_policy: 0.0001
 lr_value: 0.001

 clip_importance_ratio: True
 use_kl_penalty: False
 use_rollback: False
 use_tr_ppo: False
 use_truly_ppo: False
 use_gmom: False
 weiszfeld_iterations: 10

 rb_alpha: 0.3
 kl_target: 0.35
 start_beta: 1.0

 use_projection: False
 proj_type: 'None'
 mean_bound: 0.0
 cov_bound: 0.0
 trust_region_coeff: 0.0
 entropy_schedule: 'None'
 scale_prec: True
 entropy_eq: False
 entropy_first: True
 target_entropy: 0

 use_gae: True
 use_td: False
 use_disc_as_adv: False